name: voting_system_mobile
description: This is the Mobile Part of the Voting System

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # sending and receiving information from server
  http: ^0.13.2

  # apple icon pack
  cupertino_icons: ^1.0.2

  # country code picker for phones
  country_code_picker: ^2.0.1

  # the font awesome icon pack
  font_awesome_flutter: ^9.0.0

  # store and load data to/from device
  shared_preferences: ^2.0.5

  # localize date format
  intl: ^0.17.0

  # set up unique list of objects
  darq: ^1.1.1

  # app wide state management
  provider: ^5.0.0

  # loading animation
  flutter_spinkit: ^5.0.0

  # connectivity checker
  connectivity: ^3.0.6

  # custom radio
  custom_radio_grouped_button: ^1.0.6+1

  # socket io
  socket_io_client: ^1.0.1

  # native splash screen
  flutter_native_splash: ^1.2.0

  # Firebase core
  firebase_core: ^1.3.0

  # Cloud Firestore
  cloud_firestore: ^2.3.0

  # Firebase Storage
  firebase_storage: ^9.0.0

  # Image picker
  image_picker: ^0.8.1+3

  # permission handler
  permission_handler: ^8.1.2

  # http request and response handler for image upload and fetching
  dio: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/

